// Generated by core/tools/gen-design.mjs from core/src/design.ts.
// Do not edit by hand. Trueline is two programs and a palette maintained
// twice disagrees with itself -- which a person sees as the same thing
// being two colours either side of a web view. Regenerate with:
// 
//     node --experimental-strip-types core/tools/gen-design.mjs

import SwiftUI
import UIKit

/// What the app looks like, on the Swift side.
///
/// Every value here is generated from `core/src/design.ts`, which the web
/// screens read through `web/src/tokens.css`. That is the whole point: the tab
/// bar is Swift and the room screen inside it is a web view, and a person
/// holding the phone must not be able to tell where one stops.
///
/// The colours are `UIColor` closures rather than asset-catalogue colours, so
/// the light and dark values sit beside each other in this file where they can
/// be read together, and so there is nothing to keep in step in a second place.
enum Ink {
    /// #F5F7F8 in the light, #0F1316 in the dark.
    static let ground = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 15/255, green: 19/255, blue: 22/255, alpha: 1)
            : UIColor(red: 245/255, green: 247/255, blue: 248/255, alpha: 1)
    })

    /// #FFFFFF in the light, #1B2126 in the dark.
    static let raise = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 27/255, green: 33/255, blue: 38/255, alpha: 1)
            : UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 1)
    })

    /// #EDF0F2 in the light, #171C20 in the dark.
    static let sunk = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 23/255, green: 28/255, blue: 32/255, alpha: 1)
            : UIColor(red: 237/255, green: 240/255, blue: 242/255, alpha: 1)
    })

    /// #14181B in the light, #E4E7E9 in the dark.
    static let ink = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 228/255, green: 231/255, blue: 233/255, alpha: 1)
            : UIColor(red: 20/255, green: 24/255, blue: 27/255, alpha: 1)
    })

    /// #4B545B in the light, #D8DDE1 in the dark.
    static let quiet = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 216/255, green: 221/255, blue: 225/255, alpha: 1)
            : UIColor(red: 75/255, green: 84/255, blue: 91/255, alpha: 1)
    })

    /// #687178 in the light, #C2C9CE in the dark.
    static let faint = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 194/255, green: 201/255, blue: 206/255, alpha: 1)
            : UIColor(red: 104/255, green: 113/255, blue: 120/255, alpha: 1)
    })

    /// #DFE3E6 in the light, #2B3238 in the dark.
    static let rule = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 43/255, green: 50/255, blue: 56/255, alpha: 1)
            : UIColor(red: 223/255, green: 227/255, blue: 230/255, alpha: 1)
    })

    /// #E9ECEE in the light, #232A2F in the dark.
    static let hair = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 35/255, green: 42/255, blue: 47/255, alpha: 1)
            : UIColor(red: 233/255, green: 236/255, blue: 238/255, alpha: 1)
    })

    /// #8F4408 in the light, #F0A85C in the dark.
    static let scanned = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 240/255, green: 168/255, blue: 92/255, alpha: 1)
            : UIColor(red: 143/255, green: 68/255, blue: 8/255, alpha: 1)
    })

    /// #FDF3E7 in the light, #2A1C10 in the dark.
    static let scannedSoft = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 42/255, green: 28/255, blue: 16/255, alpha: 1)
            : UIColor(red: 253/255, green: 243/255, blue: 231/255, alpha: 1)
    })

    /// #EBC9A2 in the light, #4A3117 in the dark.
    static let scannedEdge = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 74/255, green: 49/255, blue: 23/255, alpha: 1)
            : UIColor(red: 235/255, green: 201/255, blue: 162/255, alpha: 1)
    })

    /// #1F7A4D in the light, #6FD39C in the dark.
    static let measured = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 111/255, green: 211/255, blue: 156/255, alpha: 1)
            : UIColor(red: 31/255, green: 122/255, blue: 77/255, alpha: 1)
    })

    /// #EDF7F1 in the light, #0F241A in the dark.
    static let measuredSoft = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 15/255, green: 36/255, blue: 26/255, alpha: 1)
            : UIColor(red: 237/255, green: 247/255, blue: 241/255, alpha: 1)
    })

    /// #A9D6BE in the light, #1E4632 in the dark.
    static let measuredEdge = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 30/255, green: 70/255, blue: 50/255, alpha: 1)
            : UIColor(red: 169/255, green: 214/255, blue: 190/255, alpha: 1)
    })

    /// #5A6570 in the light, #8B979F in the dark.
    static let derived = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 139/255, green: 151/255, blue: 159/255, alpha: 1)
            : UIColor(red: 90/255, green: 101/255, blue: 112/255, alpha: 1)
    })

    /// #5B3C9E in the light, #B79DEE in the dark.
    static let adjusted = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 183/255, green: 157/255, blue: 238/255, alpha: 1)
            : UIColor(red: 91/255, green: 60/255, blue: 158/255, alpha: 1)
    })

    /// #F3EFFC in the light, #1E1730 in the dark.
    static let adjustedSoft = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 30/255, green: 23/255, blue: 48/255, alpha: 1)
            : UIColor(red: 243/255, green: 239/255, blue: 252/255, alpha: 1)
    })

    /// #C6B4EC in the light, #3A2D5C in the dark.
    static let adjustedEdge = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 58/255, green: 45/255, blue: 92/255, alpha: 1)
            : UIColor(red: 198/255, green: 180/255, blue: 236/255, alpha: 1)
    })

    /// #B8590A in the light, #D06A12 in the dark.
    static let accent = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 208/255, green: 106/255, blue: 18/255, alpha: 1)
            : UIColor(red: 184/255, green: 89/255, blue: 10/255, alpha: 1)
    })

    /// #FFFFFF in the light, #FFFFFF in the dark.
    static let onAccent = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 1)
            : UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 1)
    })

    /// #A31212 in the light, #F08A8A in the dark.
    static let refuse = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 240/255, green: 138/255, blue: 138/255, alpha: 1)
            : UIColor(red: 163/255, green: 18/255, blue: 18/255, alpha: 1)
    })

    /// #FCEFEF in the light, #2A1212 in the dark.
    static let refuseSoft = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 42/255, green: 18/255, blue: 18/255, alpha: 1)
            : UIColor(red: 252/255, green: 239/255, blue: 239/255, alpha: 1)
    })

    /// #E9B4B4 in the light, #4E2020 in the dark.
    static let refuseEdge = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 78/255, green: 32/255, blue: 32/255, alpha: 1)
            : UIColor(red: 233/255, green: 180/255, blue: 180/255, alpha: 1)
    })

    /// #2C6FA8 in the light, #5FA0D0 in the dark.
    static let focus = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 95/255, green: 160/255, blue: 208/255, alpha: 1)
            : UIColor(red: 44/255, green: 111/255, blue: 168/255, alpha: 1)
    })

    /// #EDF4FA in the light, #0F1E29 in the dark.
    static let focusSoft = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 15/255, green: 30/255, blue: 41/255, alpha: 1)
            : UIColor(red: 237/255, green: 244/255, blue: 250/255, alpha: 1)
    })

    /// #A9C9E2 in the light, #254559 in the dark.
    static let focusEdge = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: 37/255, green: 69/255, blue: 89/255, alpha: 1)
            : UIColor(red: 169/255, green: 201/255, blue: 226/255, alpha: 1)
    })
}

/// The faces on this side, which are the SYSTEM's, deliberately.
///
/// The web screens are set in Archivo and IBM Plex Mono, shipped inside the
/// app. This side is not, and that is a decision rather than an omission:
///
///   - What is native here is CHROME -- a tab bar, a navigation title, a list
///     of rooms. Apple's own apps set that in the system face, and a tab bar in
///     a custom grotesque reads as a website pretending to be an app.
///   - Dynamic Type keeps working. Somebody who has turned their text up gets
///     it turned up, which a fixed-size custom font quietly refuses.
///   - UIAppFonts cannot load a woff2. Using Archivo here would mean shipping
///     the same typeface twice in two formats, and two copies of a font is two
///     things to keep in step for a tab bar nobody measures anything on.
///
/// Nothing native displays a measurement. The moment something does, it gets
/// "mono" below and the reason above stops applying to it.
enum Face {
    /// Chrome: titles, labels, list rows.
    static func sans(_ style: Font.TextStyle = .body, weight: Font.Weight = .regular) -> Font {
        .system(style).weight(weight)
    }

    /// Any number, if this side ever shows one. Tabular, so a column lines up
    /// and a digit that changed is visible where it changed.
    static func mono(_ style: Font.TextStyle = .body, weight: Font.Weight = .regular) -> Font {
        .system(style, design: .monospaced).weight(weight)
    }
}

/// The type scale. Six steps, because a scale somebody can hold in their head
/// is a scale that gets used.
enum Size {
    static let micro: CGFloat = 10
    static let small: CGFloat = 12
    static let body: CGFloat = 15
    static let lead: CGFloat = 17
    static let head: CGFloat = 21
    static let figure: CGFloat = 27
}

/// Spacing, on a four-grid. A phone screen with a tape reading on it is dense
/// by nature, and an eight-grid rounds every tight thing up to loose.
enum Space {
    static let hair: CGFloat = 2
    static let tight: CGFloat = 4
    static let snug: CGFloat = 6
    static let step: CGFloat = 9
    static let room: CGFloat = 12
    static let apart: CGFloat = 15
    static let wide: CGFloat = 18
    static let gap: CGFloat = 24
}

/// Corner radii. Small, deliberately: nothing on a measuring instrument is
/// rounded.
enum Radius {
    static let chip: CGFloat = 2
    static let control: CGFloat = 4
    static let surface: CGFloat = 6
}

/// The smallest a target may be. Apple says 44; this app is used with a tape in
/// the other hand and sometimes a glove on.
enum Touch {
    static let least: CGFloat = 44
    static let comfortable: CGFloat = 48
}
