// Generated by core/tools/gen-entitlement.mjs from core/src/entitlement.ts.
// Do not edit by hand: the TypeScript is the source, because the same gate has
// to hold on both sides of this app and a list maintained twice disagrees with
// itself. Regenerate with:
//
//     node --experimental-strip-types core/tools/gen-entitlement.mjs

import Foundation

/// What is free, what is paid, and the sentence said when something is locked.
enum Entitlement {

    enum Feature: String, CaseIterable, Hashable {
        case scan
        case measure
        case plan
        case room3d
        case edit
        case dimensions
        case takeoff
        case pricing
        case proposal
        case signature
        case changeOrders
        case insurance
        case exports
        case priceList
        case unlimitedRooms
    }

    /// Everything anybody gets, forever, without an account.
    static let free: [Feature] = [.scan, .measure, .plan, .room3d, .edit, .dimensions]

    /// Everything a subscription unlocks, in the order it is explained.
    static let paid: [Feature] = [.takeoff, .pricing, .proposal, .signature, .changeOrders, .insurance, .exports, .priceList, .unlimitedRooms]

    /// How many rooms are kept without a subscription.
    static let freeRooms = 1

    /// That count, as a sentence somebody can read.
    ///
    /// The paywall interpolated the bare count into a sentence that had already
    /// been written plural, so with the free tier at one it read as a digit
    /// followed by a plural noun — on the one screen in the app that asks for
    /// money, to exactly the audience being asked. `core/src/entitlement.ts`
    /// had already solved this with `inWords`; the Swift half had no
    /// equivalent, which is how a number reached a sentence with nothing
    /// between them.
    ///
    /// Small numbers go in words, the way a person says them. Above six a digit
    /// is what somebody reads more easily, which is the same line the
    /// TypeScript draws.
    static func roomsKept(_ count: Int = freeRooms) -> String {
        let counted = ["no", "one", "two", "three", "four", "five", "six"]
        let said = count >= 0 && count < counted.count ? counted[count] : String(count)
        return "\(said) \(count == 1 ? "room" : "rooms")"
    }

    static func isFree(_ feature: Feature) -> Bool { free.contains(feature) }

    static func allowed(_ feature: Feature, subscribed: Bool) -> Bool {
        subscribed || isFree(feature)
    }

    static func title(of feature: Feature) -> String {
        switch feature {
        case .scan: return "Scan a room"
        case .measure: return "Measure by hand"
        case .plan: return "The drawing"
        case .room3d: return "The 3D view"
        case .edit: return "Correcting the room"
        case .dimensions: return "Dimensions and floor area"
        case .takeoff: return "The takeoff"
        case .pricing: return "Your rates, applied"
        case .proposal: return "Proposals"
        case .signature: return "Signatures"
        case .changeOrders: return "Change orders"
        case .insurance: return "Insurance mode"
        case .exports: return "Every export"
        case .priceList: return "Your supplier's prices"
        case .unlimitedRooms: return "Unlimited rooms"
        }
    }

    /// What the thing does, never that it is locked.
    static func describe(_ feature: Feature) -> String {
        switch feature {
        case .scan: return "Scan a room with the phone."
        case .measure: return "Walk a room and place its corners by hand."
        case .plan: return "The drawing, with its dimensions, doors and windows."
        case .room3d: return "The same room in three dimensions."
        case .edit: return "Rename, move, split and correct anything on the plan."
        case .dimensions: return "How far the room reaches each way, and its floor area."
        case .takeoff: return "Every quantity in the room — floor, ceiling, wall face, baseboard, framing, openings — worked out from the measurements, with every door and window taken off."
        case .pricing: return "Your rates against those quantities, so the room prices itself. Set a rate once and every room you measure afterwards uses it."
        case .proposal: return "A document a homeowner says yes to: the work in sentences, the price, what is not included, and options to choose between."
        case .signature: return "Signed in the kitchen, with the record that makes it stand up — who signed, when, what they agreed to, and a fingerprint of the document."
        case .changeOrders: return "The signed scope freezes. Everything that changes afterwards comes back as a priced line, so scope creep stops being an argument and becomes a list."
        case .insurance: return "Mark the damage on the wall, log the moisture readings, attach the photographs, and send the adjuster one document."
        case .exports: return "The drawing, the client file, CAD, the field sheet, the claim PDF and the whole job in one archive."
        case .priceList: return "Import a supplier's price list and price against what you actually pay."
        case .unlimitedRooms: return "More than one room kept at once. Every room already on the phone stays there and stays readable — this is about writing down a new one, never about taking away work somebody has already done."
        }
    }
}
