/**
 * Writes the design tokens into both halves of the app, from one source.
 *
 *     node --experimental-strip-types core/tools/gen-design.mjs
 *     node --experimental-strip-types core/tools/gen-design.mjs --check
 *
 * `core/src/design.ts` holds the palette, the type scale, the spacings and the
 * radii. This writes:
 *
 *   - `web/src/tokens.css`      custom properties, with a dark set
 *   - `ios/Trueline/Design.swift`  the same values as SwiftUI colours
 *
 * ScanToBid is two programs and the person holding the phone must not be able to
 * tell. A palette maintained twice is a palette that disagrees with itself, and
 * the disagreement shows up as the same thing being two colours on either side
 * of a web view. `Entitlement.swift` already keeps this discipline for the
 * subscription gate; this is the same rule for what the app looks like.
 *
 * `--check` fails when what is on disk is not what this would write, which is
 * what the pre-push hook runs. A generated file that has gone stale is worse
 * than no generated file, because it looks maintained.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');

const { TONES, TYPE, SIZE, SPACE, RADIUS, TOUCH } = await import(
  join(root, 'core', 'src', 'design.ts')
);

const HEAD = (tool) =>
  `Generated by core/tools/gen-design.mjs from core/src/design.ts.\n` +
  `Do not edit by hand. ScanToBid is two programs and a palette maintained\n` +
  `twice disagrees with itself -- which a person sees as the same thing\n` +
  `being two colours either side of a web view. Regenerate with:\n\n` +
  `    node --experimental-strip-types core/tools/gen-design.mjs\n` +
  (tool ? `\n${tool}\n` : '');

/** `#14181B` to `20 24 27`, so Tailwind's `/50` opacity modifiers work. */
function channels(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex);
  if (!m) throw new Error(`${hex} is not a six-digit hex colour.`);
  const n = parseInt(m[1], 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/* ------------------------------------------------------------------- CSS */

const cssVars = (which) =>
  Object.entries(TONES)
    .map(([name, tone]) => `  --c-${kebab(name)}: ${channels(tone[which])};`)
    .join('\n');

const css = `/* ${HEAD('').trim().split('\n').join('\n   ')} */

/*
   Colours are stored as SPACE-SEPARATED RGB CHANNELS rather than as hex,
   because Tailwind writes \`rgb(var(--c-ground) / <alpha-value>)\` and that only
   works on channels. It is also why \`bg-ground/95\` keeps working: a hex in a
   custom property would silently drop the opacity and the fixed bars would go
   solid without anybody noticing.
*/
:root {
${cssVars('light')}

  --font-sans: ${TYPE.sans};
  --font-mono: ${TYPE.mono};

${Object.entries(SIZE).map(([k, v]) => `  --size-${k}: ${v}px;`).join('\n')}

${Object.entries(SPACE).map(([k, v]) => `  --space-${k}: ${v}px;`).join('\n')}

${Object.entries(RADIUS).map(([k, v]) => `  --radius-${k}: ${v}px;`).join('\n')}

${Object.entries(TOUCH).map(([k, v]) => `  --touch-${k}: ${v}px;`).join('\n')}
}

/*
   The basement. Following the phone rather than offering a switch: somebody
   walking from a driveway into a basement is not going to stop and change a
   setting, and the operating system already knows.
*/
@media (prefers-color-scheme: dark) {
  :root {
${cssVars('dark').split('\n').map((l) => '  ' + l).join('\n')}
  }
}

/*
   Paper, always.

   This is the rule the whole direction rests on: the TOOL follows the phone,
   and anything that leaves the app as a DOCUMENT is paper. A blueprint printed
   in the dark palette would be a sheet of black ink going to a homeowner, and
   the first person to find out would be whoever owns the printer.

   Because it resets the tokens rather than restyling the components, every
   drawing, every schedule and every document in the app prints correctly
   without knowing this block exists -- including ones written after it.
*/
@media print {
  :root {
${cssVars('light').split('\n').map((l) => '  ' + l).join('\n')}
  }
}
`;

/* ----------------------------------------------------------------- Swift */

function swiftColour(name, tone) {
  const [lr, lg, lb] = channels(tone.light).split(' ');
  const [dr, dg, db] = channels(tone.dark).split(' ');
  return `    /// ${tone.light} in the light, ${tone.dark} in the dark.
    static let ${name} = Color(UIColor { trait in
        trait.userInterfaceStyle == .dark
            ? UIColor(red: ${dr}/255, green: ${dg}/255, blue: ${db}/255, alpha: 1)
            : UIColor(red: ${lr}/255, green: ${lg}/255, blue: ${lb}/255, alpha: 1)
    })`;
}

const swift = `// ${HEAD('').trim().split('\n').join('\n// ')}

import SwiftUI
import UIKit

/// What the app looks like, on the Swift side.
///
/// Every value here is generated from \`core/src/design.ts\`, which the web
/// screens read through \`web/src/tokens.css\`. That is the whole point: the tab
/// bar is Swift and the room screen inside it is a web view, and a person
/// holding the phone must not be able to tell where one stops.
///
/// The colours are \`UIColor\` closures rather than asset-catalogue colours, so
/// the light and dark values sit beside each other in this file where they can
/// be read together, and so there is nothing to keep in step in a second place.
enum Ink {
${Object.entries(TONES).map(([name, tone]) => swiftColour(name, tone)).join('\n\n')}
}

/// The faces on this side, which are the SYSTEM's, deliberately.
///
/// The web screens are set in Archivo and IBM Plex Mono, shipped inside the
/// app. This side is not, and that is a decision rather than an omission:
///
///   - What is native here is CHROME -- a tab bar, a navigation title, a list
///     of rooms. Apple's own apps set that in the system face, and a tab bar in
///     a custom grotesque reads as a website pretending to be an app.
///   - Dynamic Type keeps working. Somebody who has turned their text up gets
///     it turned up, which a fixed-size custom font quietly refuses.
///   - UIAppFonts cannot load a woff2. Using Archivo here would mean shipping
///     the same typeface twice in two formats, and two copies of a font is two
///     things to keep in step for a tab bar nobody measures anything on.
///
/// Nothing native displays a measurement. The moment something does, it gets
/// "mono" below and the reason above stops applying to it.
enum Face {
    /// Chrome: titles, labels, list rows.
    static func sans(_ style: Font.TextStyle = .body, weight: Font.Weight = .regular) -> Font {
        .system(style).weight(weight)
    }

    /// Any number, if this side ever shows one. Tabular, so a column lines up
    /// and a digit that changed is visible where it changed.
    static func mono(_ style: Font.TextStyle = .body, weight: Font.Weight = .regular) -> Font {
        .system(style, design: .monospaced).weight(weight)
    }
}

/// The type scale. Six steps, because a scale somebody can hold in their head
/// is a scale that gets used.
enum Size {
${Object.entries(SIZE).map(([k, v]) => `    static let ${k}: CGFloat = ${v}`).join('\n')}
}

/// Spacing, on a four-grid. A phone screen with a tape reading on it is dense
/// by nature, and an eight-grid rounds every tight thing up to loose.
enum Space {
${Object.entries(SPACE).map(([k, v]) => `    static let ${k}: CGFloat = ${v}`).join('\n')}
}

/// Corner radii. Small, deliberately: nothing on a measuring instrument is
/// rounded.
enum Radius {
${Object.entries(RADIUS).map(([k, v]) => `    static let ${k}: CGFloat = ${v}`).join('\n')}
}

/// The smallest a target may be. Apple says 44; this app is used with a tape in
/// the other hand and sometimes a glove on.
enum Touch {
${Object.entries(TOUCH).map(([k, v]) => `    static let ${k}: CGFloat = ${v}`).join('\n')}
}
`;

const files = [
  [join(root, 'web', 'src', 'tokens.css'), css],
  [join(root, 'ios', 'Trueline', 'Design.swift'), swift],
];

/**
 * Every `--c-` name anything reaches for, against the ones `tokens.css`
 * declares.
 *
 * The generated files matching their source was never the whole question. A
 * third file — `web/tailwind.config.js` — names these tokens too, and it was
 * naming ten of them wrong: it interpolated the TypeScript's `refuseSoft`
 * straight in as `--c-refuseSoft`, where the generator writes
 * `--c-refuse-soft`. CSS does not treat an unresolvable `var()` as absent. It
 * invalidates the whole declaration, so `background-color` fell back to
 * transparent — silently, with no error in any console — and fifteen utilities
 * painted nothing at all: `bg-red-50`, `bg-amber-50`, `bg-emerald-50`,
 * `bg-sky-50`, `bg-violet-50`, five border tints, and three pressed states.
 * A red refusal banner was a transparent rectangle.
 *
 * It is the same defect that put a black square on the claim document. So the
 * check is the same shape as that fix: every token anybody names has to be a
 * token that is declared.
 */
function tokensNobodyDeclares(declaredIn) {
  const declared = new Set(
    [...declaredIn.matchAll(/^\s*(--c-[a-z0-9-]+)\s*:/gim)].map((m) => m[1].toLowerCase())
  );
  const missing = [];
  for (const where of ['web/tailwind.config.js', 'web/src/index.css']) {
    let text = '';
    try { text = readFileSync(join(root, where), 'utf8'); } catch { continue; }
    for (const m of text.matchAll(/--c-[A-Za-z0-9-]+/g)) {
      // A template hole rather than a name: `--c-${name}` is built at run time
      // and cannot be judged here. The `cssName` it is built through is what
      // this check exists to hold honest, and the built CSS below is where that
      // is caught for real.
      if (m[0].includes('$')) continue;
      if (!declared.has(m[0].toLowerCase())) missing.push(`${where}: ${m[0]}`);
    }
  }
  // And the built stylesheet, which is the only place the two meet. A config
  // that reads correctly and a generator that reads correctly can still produce
  // a rule that resolves to nothing.
  for (const sheet of globCss(join(root, 'web', 'dist', 'assets'))) {
    for (const m of sheet.text.matchAll(/var\((--c-[A-Za-z0-9-]+)\)/g)) {
      if (!declared.has(m[1].toLowerCase())) missing.push(`${sheet.name}: ${m[1]}`);
    }
  }
  return [...new Set(missing)];
}

function globCss(dir) {
  try {
    return readdirSync(dir)
      .filter((name) => name.endsWith('.css'))
      .map((name) => ({ name, text: readFileSync(join(dir, name), 'utf8') }));
  } catch {
    // No build here yet. `npm run verify` builds before this runs; a bare
    // `check-tokens` on a clean tree checks the two source files and says so.
    return [];
  }
}

if (process.argv.includes('--check')) {
  let bad = false;
  for (const [path, want] of files) {
    let have = '';
    try { have = readFileSync(path, 'utf8'); } catch { /* not written yet */ }
    if (have !== want) {
      console.error(`${path} is not what core/src/design.ts says.`);
      bad = true;
    }
  }
  const missing = tokensNobodyDeclares(css);
  if (missing.length > 0) {
    console.error('These colour tokens are named but never declared, so they paint nothing:');
    for (const one of missing) console.error(`  ${one}`);
    console.error('A var() that resolves to nothing does not fall back -- it voids the whole');
    console.error('declaration, so the colour becomes transparent or black with no error.');
    bad = true;
  }
  if (bad) {
    console.error('Regenerate:  node --experimental-strip-types core/tools/gen-design.mjs');
    process.exit(1);
  }
  console.log('tokens.css and Design.swift match the TypeScript they are generated from');
  console.log('and every --c- token named anywhere is one that tokens.css declares');
} else {
  for (const [path, want] of files) {
    writeFileSync(path, want);
    console.log(`wrote ${path}`);
  }
}
